### PR TITLE
fix: convert empty space to `%20` when render hyperlinks

### PR DESCRIPTION
**Pull request by XhstormR**
fix https://github.com/eza-community/eza/issues/843

https://docs.rs/percent-encoding/latest/percent_encoding/fn.utf8_percent_encode.html

### CODE REVIEW

**Comment by XhstormR** [comment]
@cafkafk Do you know who else could review this PR? Thanks

**Comment by cafkafk** [comment]
> @cafkafk Do you know who else could review this PR? Thanks

Anyone in commiters could, but reviews are volunteering, so there's no strict timeframe. Sadly none of us are currently paid to do this fulltime, but as soon as someone is available I'm sure they'll review it.

I usually do some batch reviews a few times a month, where I might look at this :)

**Comment by XhstormR** [comment]
@cafkafk Do you have time to check it now? it's a small change.

**Comment by XhstormR** [comment]
ping

**Review by PThorpe92 — APPROVED** [review]
Sorry this sat for so long. Looks good to me :+1: 

Can you rebase + fix the conflicts?

**Comment by XhstormR** [comment]
@PThorpe92 ping, i have resolve the conflicts.

**Review by PThorpe92 — APPROVED** [review]

**Pull request merged**
