### PR TITLE
Issue 872 group directories

### PR DESCRIPTION
**Pull request by erwinvaneijk**
This PR introduces the option to show directories *last* in the listing.

Fixes: #872

### CODE REVIEW

**Comment by astr0gator** [comment]
Hi guys,
It would be amazing if you could merge this helpful PR 🙏

**Comment by 20manas** [comment]
Hi. @cafkafk is there anything pending in this PR? Can it be merged?

**Comment by fightingdreamer** [comment]
I would love see this merged — it's the most natural way of browsing node based file-systems.

**Review by cafkafk — CHANGES_REQUESTED** [review]
Since people keep commenting on this PR, this is currently in draft, indicating it's not ready for review. Further, before review it would first need to have conflicts resolved.

**Comment by erwinvaneijk** [comment]
> Since people keep commenting on this PR, this is currently in draft, indicating it's not ready for review. Further, before review it would first need to have conflicts resolved.

I'm working on it again, since I saw the comments about this PR being useful.

**Pull request closed without merging**
