### PR TITLE
feat: document and change output for --git-repos

### PR DESCRIPTION
**Pull request by PThorpe92**
image
I think this is much clearer, in reference to #281 

with no-status
image

### CODE REVIEW

**Review by cafkafk — CHANGES_REQUESTED** [review]
Maybe this should be under a `--git-repos` entry. We should probably also explain the difference between `--git-repos` and `--git-repos-no-status`. 

Refs: #62, https://github.com/ogham/exa/pull/797

**Comment by PThorpe92** [comment]
> Maybe this should be under a `--git-repos` entry. We should probably also explain the difference between `--git-repos` and `--git-repos-no-status`.

Ok because my other PR changes that same area of documentation, I'll wait till that is merged and redo this one just to avoid a conflict

**Comment by cafkafk** [comment]
> > Maybe this should be under a `--git-repos` entry. We should probably also explain the difference between `--git-repos` and `--git-repos-no-status`.
> 
> Ok because my other PR changes that same area of documentation, I'll wait till that is merged and redo this one just to avoid a conflict

Sorry, I didn't see that >_<

**Comment by cafkafk** [comment]
https://github.com/eza-community/eza/pull/272 is merged now

**Review by gierens — APPROVED** [review]

**Comment by holmesrichards** [comment]
Given the existence of EXA_COLORS and the [discussion](https://github.com/eza-community/eza/issues/139) of themeing with config files, would it be better not to include potentially wrong information about the symbol colors in the documentation?

**Review by cafkafk — APPROVED** [review]
LGTM, and now I actually understand the symbols, thanks!

**Comment by PThorpe92** [comment]
The reason I added the colors to the man page was because it will display a `-` for a git directory if unknown status, however it will also use the same `-` for a non-git directory. This is indeed one of the options I would like to be able to theme in the future, so the question is... do we want another symbol for unknown status instead of relying on a color?

**Review by cafkafk — APPROVED** [review]

**Comment by holmesrichards** [comment]
This uses
```
            f::SubdirGitRepoStatus::GitClean => style.fg(Color::Green).paint("| "),
            f::SubdirGitRepoStatus::GitDirty => style.bold().fg(Color::Red).paint("+ "),
            f::SubdirGitRepoStatus::GitUnknown => style.fg(Color::Green).bold().paint("~ "),
```

Might I suggest using something like `colours.new().paint("N")` for `|` and `~` and  `colours.modified().paint("M")` for `+`? With or without `bold()`, but that should made be consistent.

**Pull request merged**
