### PR TITLE
fix: adjust change width calculations for hyperlink and classify

### LINKED ISSUE #267: bug: incorrect grid width when using --hyperlink --classify
If eza does something unexpected, or its output looks wrong, or it displays an error on the screen, or if it outright crashes, then please include the following information in your report:

- The version of eza being used (`eza --version`)
- The command-line arguments you are using
- Your operating system and hardware platform

If it’s a crash, please include the full text of the crash that gets printed to the screen. If you’re seeing unexpected behaviour, a screenshot of the issue will help a lot.

---
shot-2023-09-12-101825

This version is packaged by Arch Linux.

### PR DESCRIPTION
**Pull request by cgorski**
This fix adjusts the calculations used when hyperlink and classify options are both specified on the command line, correcting behavior that would cause columns to be misaligned.

Resolves #267

### CODE REVIEW

**Comment by cgorski** [comment]
I'm trying to write a test for this, but 

`bin.name = "eza"`
`args = "tests/itest --hyperlink --classify --width=10"`

does not seem to correctly set the width within a test.

**Comment by cgorski** [comment]
It just occurred to me that when calling `classify_char()` I should be taking the length of the str and not assuming length 1. I’ll commit a fix shortly.

**Comment by cgorski** [comment]
@cafkafk do you have a suggestion on how to best write a test for this? It works on my macOS machine, but I presume when it is running on a different terminal type that other control characters are being generated and failing the test.

**Comment by cgorski** [comment]
Actually it looks like the problem is the absolute path in the hyperlinks. Not sure how to proceed.

**Comment by cafkafk** [comment]
> Actually it looks like the problem is the absolute path in the hyperlinks. Not sure how to proceed.

I think @ariasuni is probably better qualified to review this, if she has time ofc (poke)

**Comment by ariasuni** [comment]
Honestly I’m not sure. It would say: make some special code for tests, that only triggers when some env var is set (for ex: `EZA_TEST_HYPERLINK`) and that replaces the link with relative paths.

**Comment by cgorski** [comment]
I believe I can use the cfg! macro along with the environment variable you suggested to allow that env var to be read, but only during tests. I’ll investigate.

**Comment by cgorski** [comment]
@cafkafk @ariasuni after digging into this, I don't think there's a clean way to test this within the current framework without adding some custom test code.

I suggest we merge this as it fixes the bug and it leaves the codebase in an improved state, and then perhaps create another issue to consider how to structure a test.

**Review by cafkafk — CHANGES_REQUESTED** [review]
Could you squash your commits a bit? At least the ones that fail CI

**Comment by cgorski** [comment]
> Could you squash your commits a bit? At least the ones that fail CI

Done

**Review by cafkafk — DISMISSED** [review]
LGTM, thanks for fixing this bug! We'll have to see if CI accepts my commits, but if it does, this should be ready to merge :heart:

**Comment by cgorski** [comment]
> LGTM, thanks for fixing this bug! We'll have to see if CI accepts my commits, but if it does, this should be ready to merge ❤️

Happy to help! 😃

**Review by cafkafk — APPROVED** [review]

**Comment by ariasuni** [comment]
I’m not sure why this issue only affected the grid output, certainly it should have affected every output types with details or none, right?

**Pull request merged**
