### PR TITLE
test(powertest): initial powertests

### PR DESCRIPTION
**Pull request by cafkafk**
Signed-off-by: Christina Sørensen <christina@cafkafk.com>

##### Checklist while waiting for a review
- [ ] Have you performed a self review of the code?
- [ ] Have you added adequate tests?
- [ ] If this adds a feature, has completions been added for zsh and fish?
- [ ] Have you updated documentation, man pages, help?
- [ ] Have you ensured any option flags are respected?
- [ ] Does your code pass CI tests?
- [ ] Does your commit summaries follow conventional commits?

### CODE REVIEW

**Comment by PThorpe92** [comment]
@gierens 
image

care to review ? lol

**Comment by gierens** [comment]
Oh dear ... Is this becoming a contest now?! XD ... Who can get away with changing the most files in a single commit or what?! XD

**Comment by cafkafk** [comment]
> Oh dear ... Is this becoming a contest now?! XD ... Who can get away with changing the most files in a single commit or what?! XD

this was `depth=2` lol, I'll probably do this as `depth=1`, that's gonna be some 20-30 files prolly.

**Comment by MartinFillon** [comment]
I took a look at everything you did here, for me the powertest are useful and generating permutations will be cool. But as you wrote them they are not really verbose on everything. Tho we could use those with by bash script to generate those and handle all cases automatically.

**Comment by cafkafk** [comment]
Powertest is mostly working for our needs at this point, but I'll have to write some more overrides in the `powertest.toml` file and add a feature to allow prefixing flags. We need that because without it, testing stuff like `-L 4` in isolation makes little sense.

Else, should be good to go :+1:

**Comment by MartinFillon** [comment]
That is cool do they work for windows in local ? cause they fail in actions, and as I already said I have some issues with windows testing on my computer so I put them on standby

**Comment by cafkafk** [comment]
> That is cool do they work for windows in local ? cause they fail in actions, and as I already said I have some issues with windows testing on my computer so I put them on standby

These are just meant to be run on a MacOS/Linux system via Nix, specifically targeting the command line arguments. So like, these test features incidentally, but their goal is to test the clap PR.

**Review by MartinFillon — APPROVED** [review]
Didn't look through all the tests cause there is too much but the config files looks good for the moment

**Comment by cafkafk** [comment]
Gonna use https://github.com/eza-community/eza/pull/644 instead

**Pull request closed without merging**
