### PR TITLE
feat(args): Added short flag for group dirs first

### PR DESCRIPTION
**Pull request by TheBearodactyl**

### CODE REVIEW

**Review by MartinFillon — APPROVED** [review]
LGTM I don't think that anything may interfer with this

**Review by MartinFillon — APPROVED** [review]

**Comment by TheBearodactyl** [comment]
Sorry about the repeated commits, just trying to keep my fork up to date

**Comment by MartinFillon** [comment]
It is okay can you squash the completions commit into one tho ?

**Comment by MartinFillon** [comment]
and the man one

**Review by PThorpe92 — APPROVED** [review]

**Comment by TheBearodactyl** [comment]
> and the man one

@MartinFillon not at the moment. I'm currently only able to work on mobile (my laptop charger broke), and I'm having to use the GitHub website for everything, so I'm forced to commit every time i make a change. As soon as I'm able to use my laptop though, i will do that.

**Comment by MartinFillon** [comment]
It is okay

**Pull request closed without merging**
