### PR TITLE
Migrate from users lib to uzers

### PR DESCRIPTION
**Pull request by gierens**
So, I ran `cargo audit` on eza and it warns that `users` (https://github.com/ogham/rust-users) is unmaintained, which makes sense since this is how eza came about :D ... So I thought since the `uutils` fellows are working on a `term-grid` fork, I would be good if all our other deps are also clean and maintained. So I forked `rust-users` to https://github.com/gierens/uzers-rs, reviewed and merged the existing pull requests, added CI workflows, cleaned up a bit, and published it to https://crates.io/crates/uzers .

This migrates the `users` dependency to said `uzers`.

### CODE REVIEW

**Comment by gierens** [comment]
@cafkafk Since it's the same with `ansi_term` I'm going to look into this as well after lunch.

**Comment by gierens** [comment]
Also added uzers to the advisory database so `cargo audit` displays it as recommended alternative:
https://github.com/rustsec/advisory-db/pull/1751

**Comment by cafkafk** [comment]
Maybe you'd want it in the eza-community org? Right now it's just a fork right?

**Comment by gierens** [comment]
I actually thought about that, but since I'm not in the maintainers list, I wasn't able to create a repo here. Since I already commented the new url in all the issues the advisory DB created in other repos, moving would changing all those again ... so I think it's easier to keep it how it is for now.

But for the `ansi_term` fork which I'm working on right now we could do it this way. I created a request to join maintainers.

**Comment by cafkafk** [comment]
# On organization roles
> I created a request to join maintainers so I can move it there.

I looked into permissions for doing this, and I can only give "[repository roles](https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/managing-repository-roles/repository-roles-for-an-organization)" via teams on a repository level, not organizationally.

There are only two types of organizational roles:


There is a feature to add more, [but it's paid](https://docs.github.com/en/enterprise-cloud@latest/organizations/managing-user-access-to-your-organizations-repositories/managing-repository-roles/managing-custom-repository-roles-for-an-organization) :(

The best I can do in the free tier seems to be enabling all organization members to create public repositories, which I have just done.

# On team roles
I'm gonna think about the best way to structure repository permissions and then redo these very soon!

I think it makes sense to give out more permissions to you and @PThorpe92, so you can triage and do stuff like assign labels, or assigning yourself to issues etc, which I just realized today you couldn't!

Tell me if there is something you can't do that you should be able to do.

**Comment by gierens** [comment]
I'm a little mystified as to why GitHub recognizes the intended change in `Cargo.toml` as merge conflict, but ok, weird! :D

**Review by cafkafk — APPROVED** [review]
Testing of code indicates it's working, moving from an unmaintained library to a maintained fork is a pretty easy conclusion. TY, merging! (after CI)

**Pull request merged**
