### PR TITLE
ci: add Winget Releaser workflow

### LINKED ISSUE #298: Add eza to winget
Adding eza to winget would make installation on Windows much easier.

### PR DESCRIPTION
**Pull request by sitiom**
- Resolves #298

[This action](https://github.com/vedantmgoyal2009/winget-releaser) automatically generates manifests for Winget Community Repository ([microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)) and submits them.

**Before merging this:**
1. Add a **classic** PAT with `public_repo` scope as a repository secret named `WINGET_TOKEN`.

example

2. Fork https://github.com/microsoft/winget-pkgs under @eza-community. The action will use that fork for making a branch and creating a PR with the upstream [winget-pkgs](https://github.com/microsoft/winget-pkgs) repository on every release.
3. Install [Pull](https://github.com/apps/pull) on the winget-pkgs fork to ensure that it is constantly updated.

If you want to see an example of a PR created using this action, see [microsoft/winget-pkgs/pulls (Pull request has been created with WinGet Releaser)](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+sort%3Aupdated-desc+Pull+request+has+been+created+with+WinGet+Releaser).

### CODE REVIEW

**Comment by sitiom** [comment]
@cafkafk Bump. I've manually updated it for now: https://github.com/microsoft/winget-pkgs/pull/119796

**Comment by cafkafk** [comment]
I'm not comfortable with giving it my own PAS, seems like too big of a security risk. Maybe we should make an account dedicated to doing this.

**Comment by sitiom** [comment]
> I'm not comfortable with giving it my own PAS, seems like too big of a security risk. Maybe we should make an account dedicated to doing this.

Yeah, that's what the other repos do too.

**Comment by cafkafk** [comment]
Does the account with the PAS need any priveleges for the org?

**Comment by sitiom** [comment]
> Does the account with the PAS need any priveleges for the org?

Yes, but you can set the `fork-user` and use the account fork instead if you're worried.

**Review by cafkafk — APPROVED** [review]
LGTM, nescesarry setup has been done on my side. Thanks for guiding me through this :+1:

**Comment by sitiom** [comment]
Binaries are missing for https://github.com/eza-community/eza/releases/tag/v0.13.0: https://github.com/eza-community/eza/actions/runs/6226413078

**Comment by sitiom** [comment]
- https://github.com/microsoft/winget-pkgs/pull/120158

**Pull request merged**
