### PR TITLE
tests: vhs for integration testing

### PR DESCRIPTION
**Pull request by cafkafk**
##### Checklist while waiting for a review
- [ ] Have you performed a self review of the code?
- [ ] Have you added adequate tests?
- [ ] If this adds a feature, has completions been added for zsh and fish?
- [ ] Have you updated documentation, man pages, help?
- [ ] Have you ensured any option flags are respected?
- [ ] Does your code pass CI tests?
- [ ] Does your commit summaries follow conventional commits?

### CODE REVIEW

**Comment by cafkafk** [comment]
# Progress
This doesn't really show much, but the idea is you're able to record references of running certain eza commands, and then when you run this it will test against those expected references. 

You can then at some later point delete the reference, and generate it again to update it, making sure to carefully inspect the output.
pr_example_1

It does this by going through each file in `tests/tapes` (which are essentially just instructions on what to test), and then, if a tape does not have a generated reference, it makes one. If it does, it skips making one, and tries to generate a test run, then compares if the output is identical.

This is so light it could easily be run in a container, or from the flake.

Also, all the described functionality is currently *functional*, although I need to test it more thoroughly.

It does introduce a dev dependency, namely fish, but we might either code our way out of that later by making it bash, or choose a better language (this is not right now ofc). I do think fish is a good starting point.

**Comment by PThorpe92** [comment]
Go is kinda my native tongue so tomorrow I'll check it out over at VHS, see what that would look like to add and if it's within reason to implement I'll give it a shot

**Comment by cafkafk** [comment]
Here's an example of the output improvements I just made:
out

I think adding parallelism to this might be a good next step.

Another interesting thing about this approach is that it will fail fail if something is slower than we expect it to be, which might easily be because someone is on a slow CPU, but it will also serve as a way to benchmark contributions and test if they introduce lag.

> Go is kinda my native tongue so tomorrow I'll check it out over at VHS, see what that would look like to add and if it's within reason to implement I'll give it a shot

Awesome!

**Comment by PThorpe92** [comment]
Ok so that wasn't too bad at all. I have a new setting you can use in the .tape file

    DisableRender <bool>

that will keep it from running ffmpeg locally, and works for all the tests so far, I just have to write some tests for it and submit a PR :+1:

**Comment by cafkafk** [comment]
It is so awesome you could just pull a PR out your sleeve like that, hope they get time to review it soon!

**Comment by PThorpe92** [comment]
> It is so awesome you could just pull a PR out your sleeve like that, hope they get time to review it soon!

Thanks, luckily it wasn't very difficult, and it's very well written/organized code. I might still have to go add some checks and warnings for conflicting options, and probably write more tests as well.

So if there is any kind of feature, etc that you would like that might make VHS function better for our testing purposes, there is always the option of having a fork that maybe excludes some things we don't need, and we can add features that are specific to our use case. I'm kinda surprised that no such fork exists already.

**Comment by cafkafk** [comment]
So this still still has a lot of imperfections, and we're still waiting for the PR to go through, and it's not really ready for use by everyone. But already now, it would be extremely useful for me when reviewing PR's, so I really wanna get it into the source sooner than later, so I'm merging this after a quick sanity check. I'll iterate more on it in further PR's.

**Comment by cafkafk** [comment]
> So if there is any kind of feature, etc that you would like that might make VHS function better for our testing purposes, there is always the option of having a fork that maybe excludes some things we don't need, and we can add features that are specific to our use case. I'm kinda surprised that no such fork exists already.

I'm deffo keeping this option in mind, let's see how fast/flexible the charm people are first but we might add the fork to https://github.com/eza-community if we do go that route.

**Pull request merged**
