### PR TITLE
fix: Display offset for filenames with spaces

### PR DESCRIPTION
**Pull request by guillaumeboehm**
Reopening #548 in different issue.

### CODE REVIEW

**Comment by PThorpe92** [comment]
I think if you delete that #[rustfmt::skip] that was in the middle of that function. and run rustfmt, it might fix the build. that's what I was trying to do when i accidentally closed ur last PR.

**Comment by guillaumeboehm** [comment]
I don't really understand what the checks are supposed to check ? Is there a way for me to check on my machine directly without having to push to launch a job ?

**Comment by guillaumeboehm** [comment]
So much for me trying to format the code nicely myself xD

**Comment by PThorpe92** [comment]
After further review I believe we also need to check for 
```Rust
if file.name.contains(' ') || file.name.contains('\'') { 2 } else { 0 }
```
as a file name with a quote in it will cause it to be quoted as well. This is found in the check in src/options/escape.rs
```Rust 
    let needs_quotes = string.contains(' ') || string.contains('\'');
```
After that LGTM :+1:

**Review by PThorpe92 — APPROVED** [review]

**Comment by guillaumeboehm** [comment]
Also fixes #515 I believe

**Review by cafkafk — CHANGES_REQUESTED** [review]
`cargo run -- --blocksize -l --hyperlink --grid --git-repos -x --time-style "+%Y, %Y, %d%d%d - %a %u" --git --header --icons -Z -@ -o`


This bugfix targets this bug right? It's still present as far as I can tell

**Comment by cafkafk** [comment]
sorry I can't be of more help with this currently I'm a bit busy irl

**Comment by guillaumeboehm** [comment]
I didn't realize there was a different code for detailed outputs, it should be good now if I didn't mess up the formatting yet again.

**Comment by PThorpe92** [comment]
> sorry I can't be of more help with this currently I'm a bit busy irl

No worries at all :heart:



> `cargo run -- --blocksize -l --hyperlink --grid --git-repos -x --time-style "+%Y, %Y, %d%d%d - %a %u" --git --header --icons -Z -@ -o` 
> 
> This bugfix targets this bug right? It's still present as far as I can tell

Wow I can't believe I didn't see that and frankly I'm surprised even the tests didn't catch that one.. 
Testing rn

**Review by PThorpe92 — APPROVED** [review]
LGTM Thanks :+1:

**Comment by ariasuni** [comment]
> Wow I can't believe I didn't see that and frankly I'm surprised even the tests didn't catch that one..

Yeah we should probably add a test for that

**Comment by PThorpe92** [comment]
> Yeah we should probably add a test for that

Indeed. The current tests all have filenames without spaces or quotes, and none of them are longer than a few characters. Definitely not ideal

**Review by cafkafk — APPROVED** [review]
This seems to fix it, and integration tests pass, LGTM thanks for fixing this

**Comment by aarondill** [comment]
@cafkafk  @guillaumeboehm this only fixes the issue when quotes are being displayed. After this patch, using --no-quotes now results in files being offset to the left:

**Comment by guillaumeboehm** [comment]
> @cafkafk  @guillaumeboehm this only fixes the issue when quotes are being displayed. After this patch, using --no-quotes now results in files being offset to the left:
> 
> 

Oh I didn't see that option... I'll fix this when I get home.

**Comment by PThorpe92** [comment]
I got a PR ready unless you'd like to submit one @guillaumeboehm

**Comment by guillaumeboehm** [comment]
> I got a PR ready unless you'd like to submit one @guillaumeboehm 

No it's all good if you have one ! Thanks ^^

**Pull request merged**
