### PR TITLE
feat(icons): update just, add more formats

### PR DESCRIPTION
**Pull request by sweetbbak**
I added .swf for soundfont files, z64, gba, nsp, xci and charmbracelets vhs file. I also noticed that "Justfile" was uppercase, but this file is typically lowercase and that is how its generated by default using `just` with `just --init` so I added the lowercase justfile as well. Hopefully I did everything correctly and it looks okay, I tried my best to make sure I did.

### CODE REVIEW

**Review by cafkafk — CHANGES_REQUESTED** [review]
That's a very descriptive title of your PR :p

But yea, makes sense to have both versions, specially if the lowercase version is now the default (glad they changed that tbh).

Currently, this has been updated with a merge commit, which is something we forbid in eza, as it causes a lot of headaches in  02e68603603bd76a1d8eee2a619c455c645e8de0

**Comment by cafkafk** [comment]
I'd also prefer if you changed this commit to have a shorter summary, and put the rest of the text in the body of the commit:

```
feat(icons): update just, add more formats

Fix default justfile name, it is defined as 'Justfile' but 'just --init' creates the default file name as 'justfile' with a lower case 'j' - Also added the VHS file format for charmbracelets terminal recording ascii file format. Added .xci and .nsp extensions for switch games, .z64 for n64 games, .gba for gameboy games and added .swf for the sound font file format.
```

I can't force push to your branch, so you'll have to make these changes yourself

**Comment by sweetbbak** [comment]
Sorry, Im not the best at git tbh so I ended up having to mess around with things for a while. I undid the merge commit, and edited the commit message to be more to the point.

**Review by cafkafk — APPROVED** [review]
Thanks, this looks good time me, cool to have n64 and switch icons :D

**Comment by sweetbbak** [comment]
Awesome :) thanks for your help!

**Pull request merged**
