### PR TITLE
test: Implements tests using the generated directory

### PR DESCRIPTION
**Pull request by MartinFillon**
This aims to later moves unix testing to using the generated dir

### CODE REVIEW

**Review by cafkafk — COMMENTED** [review]
Could you follow up this PR (after merge, since the hash might change) by adding this to https://github.com/eza-community/eza/blob/main/.git-blame-ignore-revs. Also, ideally let's squash this except the merge commit into a single commit to make that easier

**Comment by MartinFillon** [comment]
Just FYI @cafkafk I migrated all nix tests.

**Review by cafkafk — CHANGES_REQUESTED** [review]
This worked before (at least it seemed to work), but after rebasing on top of master, `just itest` broke for me

**Comment by MartinFillon** [comment]
@cafkafk I fixed `just itest` but generation is not perfect because I have some command not found on `git` and `sudo` and I can't find where I can add those dependencies to the flake

**Comment by cafkafk** [comment]
> @cafkafk I fixed `just itest` but generation is not perfect because I have some command not found on `git` and `sudo` and I can't find where I can add those dependencies to the flake

I'll take a look.

**Comment by cafkafk** [comment]
Here's a patch that adds git, fixing sudo is gonna be less trivial, because privilege escalation in general on the host machine shouldn't be done (dunno why I haven't thought of that before).  Might specifically write some NixOS style tests for that, which allows spinning up VMs (but out of scope for this PR IMO, so shouldn't block merge).

```diff
diff --git a/flake.nix b/flake.nix
index f952da2b..d2e39c71 100644
--- a/flake.nix
+++ b/flake.nix
@@ -144,6 +144,7 @@
             buildPhase = ''bash devtools/dir-generator.sh tests/test_dir && echo "Dir generated"'';
             cargoTestOptions = opts: opts ++ ["--features nix"];
             inherit buildInputs;
+            nativeBuildInputs = with pkgs; [git];
           };
 
           # TODO: add conditionally to checks.
```
Link to download patch: https://0x0.st/HtVK.patch

**Comment by MartinFillon** [comment]
well as we need sudo for some tests creation it is kinda in range.

**Comment by MartinFillon** [comment]
poke @cafkafk

**Comment by cafkafk** [comment]
Merged as part of https://github.com/eza-community/eza/pull/644

**Pull request closed without merging**
