### PR TITLE
chore(cargo): MSRV 1.70

### PR DESCRIPTION
**Pull request by cafkafk**
This would be part of the changes making us ready for a v1.0.

# Large Command Line Programs on 1.70
- [fd](https://github.com/sharkdp/fd) does 1.70.0
- [ripgrep](https://github.com/BurntSushi/ripgrep) does 1.70
- [bat](https://github.com/sharkdp/bat) does 1.70

### CODE REVIEW

**Comment by daviessm** [comment]
Gentoo stabilised 1.71 yesterday so on that front, LGTM

**Comment by cafkafk** [comment]
> Gentoo stabilised 1.71 yesterday so on that front, LGTM

:tada: :tada: :tada:

**Review by cafkafk — COMMENTED** [review]
Linux integration tests, including sandboxed nix tests pass on this

**Comment by PThorpe92** [comment]
now we can use convenient methods like 
```Rust
is_some_and()
``` 
:D

**Review by PThorpe92 — APPROVED** [review]

**Review by ariasuni — CHANGES_REQUESTED** [review]
I think you should either update, or remove the Rust version badge in the [development section in the README](https://github.com/eza-community/eza#development--------) (and also removing the license badge because there’s already one at the top of the README).

**Comment by cafkafk** [comment]
> I think you should either update, or remove the Rust version badge in the [development section in the README](https://github.com/eza-community/eza#development--------)

Nice catch, I generally haven't had time to do much about the development section, I'd love to give it an overhaul eventually.

>  (and also removing the license badge because there’s already one at the top of the README

Yeop, makes sense, will do.

**Review by ariasuni — DISMISSED** [review]

**Review by MartinFillon — APPROVED** [review]

**Pull request merged**
