### PR TITLE
v1.0 branch - incremental clap migration improvement

### PR DESCRIPTION
**Pull request by PThorpe92**
1.0 Branch needs `main` merged in, going to do that so this diff/PR isn't so huge.

### CODE REVIEW

**Review by MartinFillon — APPROVED** [review]
This is mostly what I had done, but thank you for making it work

**Comment by PThorpe92** [comment]
What a nightmare that was.. that branch was way too far behind and that just took like 2 hours to get the two branches merged. Right now the v1.0-development branch on eza has caught up to date as i had to update it from my local machine and as u can see now the diff is a few lines.

We might want to think about rebasing off of main and applying all the changes in one commit, then getting a diff w/ main from a draft PR or something so everyone can review ( or even better, clone the v1.0 and add their changes)

**Comment by MartinFillon** [comment]
Still need to be rebased glhf to you i guess

**Comment by PThorpe92** [comment]
i think im going to just close this, and we can just open a draft PR against main to see the diff, and others can fork that branch and submit their own changes.

alll the changes are merged into v1.0 branch anyway so no sense in messing around with this one

**Pull request closed without merging**
