### PR TITLE
(exa PR) 908: Don’t show icons when piped (also add --icons={always,auto,never})

### PR DESCRIPTION
**Pull request by cafkafk**
https:/github.com/ogham/exa/pull/908

### CODE REVIEW

**Comment by PThorpe92** [comment]
hmm. Moving to 1.70 stabilizes `is_terminal()` correct?

This could use revisiting after the move for sure, but i'm fixing it now to see whats up with it.

**Comment by ariasuni** [comment]
@PThorpe92 I don’t understand why you removed the `always` option, it’s useful when you want to show icons when piped, similar to the `--colour` option.

**Comment by PThorpe92** [comment]
I'm sorry you are right, it's very possible that I fixed that locally. This just shows the initial fix of the merge conflicts here. I worked on it a bunch locally but couldn't get the `dont show in TTY | piped` option working in all cases. I really need to look at it again i've just been super busy.

**Comment by PThorpe92** [comment]
image

I think this should be all set now. The only thing is this will break everyone's alias's because the `always`, `auto`, `never` are traditionally a necessary argument flag.

**Comment by cafkafk** [comment]
> I think this should be all set now. The only thing is this will break everyone's alias's because the `always`, `auto`, `never` are traditionally a necessary argument flag.

Could we have it so `--icons` by itself implied `--icons=auto`? That way we're still almost backwards compat, and I think it's probably the most sensible option... What do you think?

**Review by cafkafk — COMMENTED** [review]
We probably need to update bash, zsh, fish, and nushell completions, as well as the manual and README.md

**Comment by cafkafk** [comment]
Could you potentially reopen this as a PR by you instead, I can't make suggestions like normally on my own PR :s

**Comment by PThorpe92** [comment]
Oh yup. gotta do the docs and completions still. Yeah it was wierd trying to request ur review on ur own PR :P I'll re open one

**Comment by PThorpe92** [comment]
Closing to open a new one.. I added more functionality

**Pull request closed without merging**
