### PR TITLE
fixed shellcheck warnings and added shellcheck to treefmt

### PR DESCRIPTION
**Pull request by 9glenda**
I was just looking around in the codebase and got some warnings from shellcheck when opening this file. 
This is still a draft since I want to to see the CI/CD checks first and test rather the script still works through manually testing it.

As soon as I tested it I will convert the draft to a normal pull request.

## To do

- [x] fix warnings
- [x] add shellcheck to the nix flake checks

### CODE REVIEW

**Comment by cafkafk** [comment]
We might add more scripts at some point, so that would be nice to have.

**Comment by cafkafk** [comment]
> #307 will add some shell scripts I think this PR should there fore be merged prior to #307 to enforce the shell check guidelines.

yea I was thinking that as well, I'll review this shortly

**Review by gierens — APPROVED** [review]
I'm also onboard with having automated shellcheck runs on scripts, great idea ... I didn't even know shellcheck and now I noticed my nvim actually also warned me about those. Since this script is at the moment just run be my every week on my computer I didn't even think anyone would care enough about it and somewhat forgot to fix those linting issues. One thing to note about shellcheck however is, that is sometimes don't gives the best suggestions or misses potential issues, like when there are two non-quoted variables in the same line. This is why I updated your changes to the script a little.

At the moment this script is afaik also not tested by CI, although that actually might be a good idea. Similar to the `apt_installation` workflow we could make one that runs this script in a Ubuntu container and then attempts to install the resulting `.deb` file.

Anyway, LGTM thanks :)

**Review by cafkafk — APPROVED** [review]
> @cafkafk what do you think, extra PR for that or just put it in this PR as well?

Probably best in a follow up PR, that way #307 isn't blocked. LGTM.

**Comment by cafkafk** [comment]
also, I should have fixed commit summaries...

**Pull request merged**
