### PR TITLE
fix(git)!: remove Repo column when using --git-repos when no git repo

### PR DESCRIPTION
**Pull request by MartinFillon**
Repo column was always showing even tho no repo was here see eza-community/eza#579 first point

### CODE REVIEW

**Review by cafkafk — CHANGES_REQUESTED** [review]
This doesn't seem to work as expected for me, `--git-repos` don't show git repos when they're there.

**Comment by MartinFillon** [comment]
>  This doesn't seem to work as expected for me, --git-repos don't show git repos when they're there.

What command did you do ?

**Comment by cafkafk** [comment]
I run `cargo run -- -l --header --git-repos ~`, and in my home directory, have repos inside dirs. I think it makes sense to display those, one of the only ways I use `--git-repos` is in a non-git folder with a lot of git folders inside of it. So the feature shouldn't just be whether or not the folder you're in is a git repo, but if it contains any git repos as well. It also has the added complication of needing to work with `--tree`, which I also tend to use with `--git-repos`.

**Comment by MartinFillon** [comment]
Okay I see the problem I am gonna try to take  look on how I could fix that.

**Review by cafkafk — APPROVED** [review]
Integration tests pass and this seems to work well! Merging...
nice-good

**Pull request merged**
