### PR TITLE
feat: Add PRQL

### PR DESCRIPTION
**Pull request by vanillajonathan**
PRQL is a modern language for transforming data — a simple, powerful, pipelined SQL replacement.

https://prql-lang.org/
https://github.com/PRQL/prql

### CODE REVIEW

**Comment by vanillajonathan** [comment]
What do you mean?

**Comment by MartinFillon** [comment]
In Contributing.md at the root you have this line:
> Requirement of conformance to [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)

You must follow it (in terms of commits) and the other around

**Comment by MartinFillon** [comment]
Thanks for the contribution. Before we can proceed with this review, you need to fix the commit summaries. You can read more in https://github.com/eza-community/eza/blob/main/CONTRIBUTING.md.

**Review by cafkafk — APPROVED** [review]
Integration tests and testing of this seems to be good now, and the commit seems to have been squashed and the summary fixed. Thanks for the contribution!

(ofc waiting for Martin to signoff before merging)

**Review by MartinFillon — APPROVED** [review]

**Comment by MartinFillon** [comment]
Good, for me rebasing and merging

**Pull request merged**
