### PR TITLE
No-Merge-Commit CI Job

### PR DESCRIPTION
**Pull request by gierens**
This adds a CI job that fails if a PR branch contains merge commits.

### CODE REVIEW

**Comment by gierens** [comment]
Ok, CI runs through, I'm now gonna merge something to see if the CI jobs fails afterwards.

**Comment by gierens** [comment]
Jap, fails, seems to work!

**Comment by gierens** [comment]
Ok, I'm removing the test merge again.

**Review by cafkafk — APPROVED** [review]
Ohh neat, LGTM, let's put it in production and see how contributors react to it :p

**Comment by cafkafk** [comment]
I did see this error https://github.com/eza-community/eza/actions/runs/10735513734

is this what the [bb84f6b](https://github.com/eza-community/eza/pull/1121/commits/bb84f6b4e83b16a7106003bf2662d86db991238b) rename solves?

**Comment by gierens** [comment]
> I did see this error https://github.com/eza-community/eza/actions/runs/10735513734
> 
> is this what the [bb84f6b](https://github.com/eza-community/eza/pull/1121/commits/bb84f6b4e83b16a7106003bf2662d86db991238b) rename solves?

I simply renamed it, so the name reflects the now more general use of the workflow.

**Comment by gierens** [comment]
Maybe that was the error I intentionally produced to test this

**Pull request merged**
