### PR TITLE
feat: mark `.git` as ignored, which hides it when using `--git-ignore`

### PR DESCRIPTION
**Pull request by ariasuni**
It makes a whole lot of sense to consider the `.git` at the root of a Git repository as ignored, since it kind is in practice.

But also, as https://github.com/ogham/exa/issues/1214 shows, it’s useful to be able to hide `.git` when using `eza --tree --all --git-ignore`.

I tested the code and confirmed it worked perfectly well in three situations:

- in eza’s repository
- in another directory (I tested it in the exa repository, `../exa` on my computer)
- in the parent directory, in an empty Git repository just created with `git init`

### CODE REVIEW

**Comment by PThorpe92** [comment]
Isn't `--git-ignored` more specific to `git` functionality? 

Wouldn't you want to list every single file/folder in a directory that is included in the repo? 
Idk how I feel specifically but the argument could definitely be made that the .git folder would be included in that list, as .git cannot ignore the .git folder.
I feel like hiding dotfiles additionally would be the option if you were not trying to list it. But I guess you might also say that someone may not want to hide all dotfiles, but they do want to hide just the .git folder?
#### Thoughts?

**Comment by ariasuni** [comment]
> Wouldn't you want to list every single file/folder in a directory that is included in the repo?

Why? The `.git` directory is not part of the Git repository. When you use `--git-ignore`, you’re likely asking to see the files that are or can be committed to the repository, and ignoring what shouldn’t be committed. It’s not useful to show `.git` if you know you’re already in a Git repository.

>  Idk how I feel specifically but the argument could definitely be made that the .git folder would be included in that list, as .git cannot ignore the .git folder.

But in fact, Git ignores `.git` so much that it’s uncommittable.

>  I feel like hiding dotfiles additionally would be the option if you were not trying to list it. But I guess you might also say that someone may not want to hide all dotfiles, but they do want to hide just the .git folder?

Idk, it makes sense to me that you would like to see every file in your repository that you care about for development, and when you’re developing using Git, you don’t care about ignored files and the `.git` directory.

**Comment by PThorpe92** [comment]
> Idk, it makes sense to me that you would like to see every file in your repository that you care about for development, and when you’re developing using Git, you don’t care about ignored files and the `.git` directory.

Yeah you are right, I definitely see your point. It just initially felt like a weird line because we are talking about the very thing that is itself doing the ignoring.. if that makes any sense. 

I think personally I don't mind seeing it, because it's just burned into me that I see that in the root of every repo. But I don't usually opt for the --git-ignore flag anyway. 

But yeah, :+1: makes sense to me now

**Review by cafkafk — APPROVED** [review]
Local manual testing and integration tests indicate this is working as expected and doesn't break anything. 

Took me a few moment to see how this makes sense to do, but it does I suppose, `.git` is implicit.

Thanks for the PR, LGTM, and merging when CI passes.

**Comment by ariasuni** [comment]
Now that I think of it, I would have liked to add some documentation in the man page about this behavior ><

**Pull request merged**
