### PR TITLE
added git-ignored color/style option

### PR DESCRIPTION
**Pull request by PThorpe92**
I tried to specify colors of ignored git files, and then saw that it was an issue on the exa page. Turns out it was an incredibly trivial fix :smile:

So I see some recent activity on the exa page, but either way I am glad to see community stepping up to maintain this project, and I will definitely do my part as a long time exa user to contribute to which ever project.

### CODE REVIEW

**Review by sbatial — CHANGES_REQUESTED** [review]
Looks good.
Please add the appropriate entry in the man-page as well. :)

**Comment by PThorpe92** [comment]
:+1: 

Now I'll take a look at some less trivial issues :wink:

**Review by sbatial — DISMISSED** [review]
Ready for merge after green checks. :+1:

**Review by cafkafk — CHANGES_REQUESTED** [review]
Commit summaries should conform to conventional commits, I'll fix that ASAP

**Comment by cafkafk** [comment]
> Commit summaries should conform to conventional commits, I'll fix that ASAP

I rebased, reworded, and tried to force push, but I think I don't have the perms to do so.

Here's what I changed the commit summaries into:

```txt
d94621e feat: add git-ignored color/style option
efb01da doc: add git-ignored color/style to manpage
```

You can make them something else ofc!

**Comment by PThorpe92** [comment]
I amended the last commit message without rebase. I'll keep it in mind for future commits

**Comment by cafkafk** [comment]
> Rebased with commit messages edited: will keep in mind for future commits. 👍

Awesome, I'll merge when tests pass, thanks for your contribution!

**Review by cafkafk — APPROVED** [review]
:+1:

**Pull request merged**
