### PR TITLE
feat: Optimize checking for empty directories when a directory has subdirectories

### PR DESCRIPTION
**Pull request by cfxegbert**
On a unix system a directory will have a link count of two when it does not have any subdirectories.  This adds a check to `is_empty_dir` to check the link count to avoid the expensive listing of a directory.

Also noticed there is not a windows version of `is_empty_dir` so eza will most likely not compile on windows.  I am not a windows developer and have no way to build or test a windows version.

### CODE REVIEW

**Comment by cafkafk** [comment]
I have to mull on this PR a bit more, but about windows support, perhaps you could keep the old behavior for non-unix systems?

**Review by cafkafk — CHANGES_REQUESTED** [review]
I have to mull on this PR a bit more, but about windows support, perhaps you could keep the old behavior for non-unix systems?

**Comment by cfxegbert** [comment]
> I have to mull on this PR a bit more, but about windows support, perhaps you could keep the old behavior for non-unix systems?

There was no behavior for non-unix systems.  When `is_empty_dir` was added only a unix version was added.  As @daviessm  pointed out #171 seems to be addressing the windows compilation issue.  I will add the original function as a windows conditional compilation.

As for a link count of 2.  The `find` command and many other utilities that walk the directory tree take advantage of the link count.  https://github.com/c9/node-gnu-tools/blob/master/findutils-src/find/find.c#L1286-L1295

The only exception I am aware of is BTRFS does not track link counts on directories.  See https://archive.kernel.org/oldwiki/btrfs.wiki.kernel.org/index.php/Project_ideas.html#Track_link_count_for_directories.  Since BTRFS always returns a link count of 1 the expensive branch of listing the directory is always used.

**Comment by cafkafk** [comment]
> > I have to mull on this PR a bit more, but about windows support, perhaps you could keep the old behavior for non-unix systems?
> 
> There was no behavior for non-unix systems.  When is_empty_dir was added only a unix version was added.

Yes, so keep the old behavior and use it for non-unix, unless it doesn't work? Am I missing something?

Anyways, I think perhaps we should introduce some benchmarks so we're not doing this blindly (criterion is preferred imo, mainly because I'm familiar with it), because if checking for filesystem to determine branch turns out to be slower than this then we're just shooting ourselves in the foot.

Maybe there is no need for a fs check, but if there is I'd like if we proved to ourselves that it was a trivial cost.

**Comment by cfxegbert** [comment]
> Maybe there is no need for a fs check, but if there is I'd like if we proved to ourselves that it was a trivial cost.

There is no need for a fs check.  The exceptions I mentioned above for BTRFS and CIFS under report the link count so the expensive branch of doing a read_dir is always run.

**Comment by cfxegbert** [comment]
Test setup was 100 directories each containing 100 files and 1 subdirectory.  On my M1 Mac Mini.  Running release build.

Command `eza --icons testdir`

Without checking nlinks (main branch):
  Time (mean ± σ):      12.8 ms ±   0.5 ms    [User: 3.7 ms, System: 8.7 ms]
  Range (min … max):    12.1 ms …  13.7 ms    202 runs

With checking nlinks (empty-directory branch):
  Time (mean ± σ):       5.1 ms ±   0.3 ms    [User: 2.0 ms, System: 2.8 ms]
  Range (min … max):     4.7 ms …   6.3 ms    398 runs

**Comment by cafkafk** [comment]
@cfxegbert could you take a look at https://github.com/eza-community/eza/pull/183/commits/f0989ec9556fa646d168e8f90cc008469b9e8a5a, I'm running out the door right now, but I tried to document these additions, feel free to reword it completely.

**Comment by cfxegbert** [comment]
> @cfxegbert could you take a look at [f0989ec](https://github.com/eza-community/eza/commit/f0989ec9556fa646d168e8f90cc008469b9e8a5a), I'm running out the door right now, but I tried to document these additions, feel free to reword it completely.

I would only add that the link count on a directory on most unix filesystems is two plus the number of subdirectories.

**Review by cafkafk — APPROVED** [review]
I tested this as much as I could on x86_64 GNU/Linux, and it does seem to work. It's a cool performance improvement, thanks for your contribution!

**Pull request merged**
