### PR TITLE
Tree-wide: Fix Windows build

### LINKED ISSUE #102: Windows Support
Right now, Eza does not support windows.

It's not really something I care to implement, specially because I don't own a windows box. 

But if anyone is up for it, you could start by making a PR with the changes to CI from here.

See: https://github.com/cafkafk/eza/pull/19

### LINKED ISSUE #169: ci: Windows build is broken after afeac47 (#61)
When checking my PR #167 doesn't break the Windows build I discovered that the Windows build has been broken for a while. Bisected to:

C:\Users\daviess\eza>git bisect bad
afeac47c13f81213b48c1d3b317ef7862061e14d is the first bad commit
commit afeac47c13f81213b48c1d3b317ef7862061e14d
Author: Christian Göttsche <cgzones@googlemail.com>
Date:   Sun Apr 25 15:00:58 2021 +0200

Which is #61.

### PR DESCRIPTION
**Pull request by daviessm**
I don't have a Mac to test on, I'd appreciate it if someone could check that build out too. This branch currently builds on both Windows and Linux.

Fixes #169 
Fixes #102

### CODE REVIEW

**Comment by cafkafk** [comment]
Looks like this failed on MacOS https://github.com/eza-community/eza/actions/runs/5991795977/job/16263711309?pr=171

I added windows to the CI, so when windows support is working and this merges, it will keep working (hopefully).

**Comment by daviessm** [comment]
Thanks @cafkafk, I pushed a couple of fixes but without a Mac I'm shooting in the dark. Can you give the CI another run (probably just the macos one, if that works then the rest can run as well)?

**Review by cafkafk — COMMENTED** [review]
This merges the #173 changes in, so we can ensure they also work on windows.

**Review by cafkafk — APPROVED** [review]
CI passes, and initial testing on x86_64 GNU/Linux indicates this is working as expected. Can someone verify this works on Windows/Mac?

**Comment by daviessm** [comment]
Windows build looks fine to me. Perhaps @cfxegbert could test this branch on Mac?

**Comment by cafkafk** [comment]
I guess we'll just test this live, I feel like it's reasonable to expect it's also working on mac, if not people will probably be quick to open an issue about it.

**Pull request merged**
