### PR TITLE
docs(README): Add feature win support

### PR DESCRIPTION
**Pull request by goyalyashpal**

### CODE REVIEW

**Comment by daviessm** [comment]
Any chance you could add a note that we only support PowerShell v6.0.0 and up? (see #404)

**Comment by goyalyashpal** [comment]
> Any chance you could add a note that we only support PowerShell v6.0.0 and up? (see #404)

aaaahhhhh windows succksss.... @microsoft please clean up ur shit storm of using stupid backslashes in paths - even u know that it sucks 🤦😡

i don't use the ms-bs tools - so, i wont be able to test this.

so, can u please share the exact wording _and_ exact version? 
even better: make a "[suggestion]" - i will "accept" that

[suggestion]: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/commenting-on-a-pull-request#adding-comments-to-a-pull-request:~:text=suggest%20a%20specific%20change

**Comment by cafkafk** [comment]
This seems like one of those low quality hacktoberfest PRs

**Comment by cafkafk** [comment]
> aaaahhhhh windows succksss.... @microsoft please clean up ur stupid shit storm legacy of using escaping backslashes in paths - even u know that it sucks 🤦😡
> 
> i don't use the ms-bs tools - so, i wont be able to test this.
> 
> so, can u please share the exact wording _and_ exact confirmed version? (i felt some ambiguity in version at #404)
> 
> ~even better: make a "[suggestion](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/commenting-on-a-pull-request#adding-comments-to-a-pull-request:~:text=suggest%20a%20specific%20change)" - i will "accept" that~ _edit: no, suggestions don't work outside the already modified hunk_

Please consider reading our code of conduct before further contributions https://github.com/eza-community/eza?tab=coc-ov-file#readme

**Comment by goyalyashpal** [comment]
> This seems like one of those low quality hacktoberfest PRs

uh oh, the timing - i didn't notice that it's october
while i agree - but it is what it is, i didn't do it to gain prs - i was expecting this point to be already there & was surprised to see it missing



> Please consider reading our code of conduct before further contributions

sorry, but windows is what it is

**Pull request closed without merging**
