### PR TITLE
feat: Added short flag for group-directories-first

### PR DESCRIPTION
**Pull request by TheBearodactyl**
just gonna be brutally honest here, i don't see why this didn't already have a short flag

### CODE REVIEW

**Review by cafkafk — CHANGES_REQUESTED** [review]
Your commit summaries need to conform to conventional commits, and this change should be contained in a single commit, so you also have to squash your commits (https://www.conventionalcommits.org/en/v1.0.0/)

You should also add completions for nushell, zsh, fish, bash, and add this to the manual and help output

**Comment by cafkafk** [comment]
also what's this about https://github.com/eza-community/eza/pull/577/commits/195988fc60ba9d9f49e32b299bdfbceed6086fe2 https://github.com/eza-community/eza/pull/577/commits/401580d89bad3024c602fd15bf4edb5bbf36ea39

**Comment by TheBearodactyl** [comment]
> also what's this about [195988f](https://github.com/eza-community/eza/commit/195988fc60ba9d9f49e32b299bdfbceed6086fe2) [401580d](https://github.com/eza-community/eza/commit/401580d89bad3024c602fd15bf4edb5bbf36ea39)

I'm currently on Android, so i can't really build locally (since rustc is kinda weird on termux), so i used GitHub actions to build it instead so i could test it in termux

**Comment by TheBearodactyl** [comment]
> Your commit summaries need to conform to conventional commits, and this change should be contained in a single commit, so you also have to squash your commits (https://www.conventionalcommits.org/en/v1.0.0/)
> 
> You should also add completions for nushell, zsh, fish, bash, and add this to the manual and help output

Oki, lemme do that

**Comment by TheBearodactyl** [comment]
Gonna close and make a new PR so that the conventional commits test passes

**Pull request closed without merging**
