### PR TITLE
feat(binaries): added statically linked binaries

### LINKED ISSUE #295: feat:  Statically-linked binaries are desired.
Would you happen to have any plan to release the statically-linked binaries?
I greatly appreciate it in advance.

### PR DESCRIPTION
**Pull request by MartinFillon**
closes #295 request

### CODE REVIEW

**Comment by cafkafk** [comment]
Sorry I haven't found time to test this yet, I'll get back to you soon!

**Comment by MartinFillon** [comment]
take your time @cafkafk

**Review by cafkafk — DISMISSED** [review]
I had to disable `aarch64-unknown-linux-gnu`, because it didn't work for me. 

BUT AWESOME.

Glad someone looked into this. Thanks so much, I'll use this for the release tomorrow!

**Review by cafkafk — APPROVED** [review]
Just changed it so static binaries were named differently, so we don't have to change the names on the release:

```
.rw-r--r-- 1.0M ces  1 Oct 07:15 eza.exe_x86_64-pc-windows-gnu.tar.gz
.rw-r--r-- 1.0M ces  1 Oct 07:15 eza.exe_x86_64-pc-windows-gnu.zip
.rw-r--r-- 1.0M ces  1 Oct 07:16 eza.exe_x86_64-pc-windows-gnu_static.tar.gz
.rw-r--r-- 1.0M ces  1 Oct 07:16 eza.exe_x86_64-pc-windows-gnu_static.zip
.rw-r--r-- 742k ces  1 Oct 07:14 eza_aarch64-unknown-linux-gnu.tar.gz
.rw-r--r-- 742k ces  1 Oct 07:14 eza_aarch64-unknown-linux-gnu.zip
.rw-r--r-- 748k ces  1 Oct 07:14 eza_arm-unknown-linux-gnueabihf.tar.gz
.rw-r--r-- 748k ces  1 Oct 07:14 eza_arm-unknown-linux-gnueabihf.zip
.rw-r--r-- 1.0M ces  1 Oct 07:15 eza_arm-unknown-linux-gnueabihf_static.tar.gz
.rw-r--r-- 1.0M ces  1 Oct 07:15 eza_arm-unknown-linux-gnueabihf_static.zip
.rw-r--r-- 803k ces  1 Oct 07:13 eza_x86_64-unknown-linux-gnu.tar.gz
.rw-r--r-- 803k ces  1 Oct 07:13 eza_x86_64-unknown-linux-gnu.zip
.rw-r--r-- 1.2M ces  1 Oct 07:13 eza_x86_64-unknown-linux-gnu_static.tar.gz
.rw-r--r-- 1.2M ces  1 Oct 07:13 eza_x86_64-unknown-linux-gnu_static.zip
.rw-r--r-- 968k ces  1 Oct 07:14 eza_x86_64-unknown-linux-musl.tar.gz
.rw-r--r-- 968k ces  1 Oct 07:14 eza_x86_64-unknown-linux-musl.zip
.rw-r--r-- 968k ces  1 Oct 07:14 eza_x86_64-unknown-linux-musl_static.tar.gz
.rw-r--r-- 968k ces  1 Oct 07:14 eza_x86_64-unknown-linux-musl_static.zip
```

**Pull request merged**
