### PR TITLE
Listen to clippy

### PR DESCRIPTION
**Pull request by sbatial**

### CODE REVIEW

**Comment by sbatial** [comment]
This should be set aside until (almost) all of the other ones have been merged to not cause a lot of merge conflicts.

**Comment by sbatial** [comment]
I think this is surpassed by #119, right?!

**Comment by cafkafk** [comment]
> I think this is surpassed by #119, right?!

Not all of it! #119 didn't touch the flake at all (iirc), so I think it makes sense to keep this PR around for the "Nix" part of this.

**Comment by cafkafk** [comment]
Also before I forget, we should probably explicitly set [cargoClippyOptions](https://github.com/nix-community/naersk) and have a comment mentioning that if it is changed, [this line of ghactions should also be changed](https://github.com/eza-community/eza/pull/120/files#diff-cd0effce06f425599e96952f4d5f684641a683f46d9909e7c74a9f8b2f03ccd3R49).

**Pull request closed without merging**
