### PR TITLE
feat: Added short flag for --group-directories-first

### PR DESCRIPTION
**Pull request by TheBearodactyl**
Sorry for the third pr, I couldn't figure out how to squash non-sequential commits, so I just decided to start over again. This will be the last one

### CODE REVIEW

**Comment by MartinFillon** [comment]
oh it is okay, fyi next time, just do `git rebase -i HEAD~<number_of_commits_before_head>`. And then You will have a menu opening explaining it.

**Review by MartinFillon — APPROVED** [review]
Looks good, simple PR but useful still

**Review by cafkafk — COMMENTED** [review]
I'm not sure I understand why upper case `W` is `group-directories-first`, perhaps there is a better flag available.

**Comment by TheBearodactyl** [comment]
> I'm not sure I understand why upper case `W` is `group-directories-first`, perhaps there is a better flag available.

i know it doesn't really have anything to do with `group-directories-first`, but both upper and lower case d are taken and i don't wanna have to switch a bunch of things around

**Comment by cafkafk** [comment]
> > I'm not sure I understand why upper case `W` is `group-directories-first`, perhaps there is a better flag available.
> 
> i know it doesn't really have anything to do with `group-directories-first`, but both upper and lower case d are taken and i don't wanna have to switch a bunch of things around

I think I'll also need you to squash this, we shouldn't have commits in the git history that exist just to restart ci

**Comment by MartinFillon** [comment]
@TheBearodactyl  you know you are not forced to close a PR you can just use it still ?

**Comment by TheBearodactyl** [comment]
> @TheBearodactyl  you know you are not forced to close a PR you can just use it still ?

i didn't close it what just happened

**Comment by TheBearodactyl** [comment]
Imma do one more pr since the Reopen pr button is greyed out for some reason
Screenshot_20231103-152923_Ortus Launcher

**Pull request closed without merging**
