### PR TITLE
REFACTOR: Improve branch visibility.

### PR DESCRIPTION
**Pull request by allaboutevemirolive**
This PR improves branch visibility by adding `space` immediately in the `ascii_art` method rather than deciding whether to add space or not at runtime. This branch visibility is based on how the original [Tree](https://github.com/Old-Man-Programmer/tree) built the branch to make it look better.

Before:

before_branch

After:

after_branch

### CODE REVIEW

**Comment by PThorpe92** [comment]
Thanks for the PR!

Personally I like it, it makes sense to me. I'm for merging if everyone else is.

**Comment by daviessm** [comment]
Do we need to worry about the failed FreeBSD check?

**Comment by PThorpe92** [comment]
image
this looks like the same exact issue from last week. I thought we merged a fix for this?

**Review by MartinFillon — DISMISSED** [review]
As per the tests, just run `just idump` then do `just itest` you will need a working nix shell, and `Just`

**Comment by allaboutevemirolive** [comment]
> As per the tests, just run `just idump` then do `just itest` you will need a working nix shell, and `Just`

Hello @MartinFillon, just to confirm, do I need to run those tests on my local machine? 

I ran `just build-release test-release`, but the command `just idump` followed by `just itest` is not working.

**Comment by MartinFillon** [comment]
yup on your local machine
and look for any ptests_file updated other can be dicarded iirc

**Comment by allaboutevemirolive** [comment]
I'm not sure why cicd didn't pass. Here I put updated files after run `idump`.

<details>
<summary>git status</summary>

$ git status
On branch branch
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   tests/cmd/absolute_recurse_unix.stdout
	modified:   tests/cmd/absolute_unix.stdout
	deleted:    tests/gen/absolute_recurse_unix.stderr
	deleted:    tests/gen/absolute_recurse_unix.stdout
	deleted:    tests/gen/absolute_unix.stderr
	deleted:    tests/gen/absolute_unix.stdout
	modified:   tests/gen/tree_long_unix.stdout
	modified:   tests/gen/tree_unix.stdout
	modified:   tests/ptests/ptest_10c50228fc1c6107.stdout
	modified:   tests/ptests/ptest_132ac9f159c3473e.stdout
	modified:   tests/ptests/ptest_1ab8279d631495b0.stdout
	modified:   tests/ptests/ptest_1e61d8c305ff6c48.stdout
	modified:   tests/ptests/ptest_2176b1b061cb7da2.stdout
	modified:   tests/ptests/ptest_298b768f6bb48dac.stdout
	modified:   tests/ptests/ptest_3259dc201df8e734.stdout
	modified:   tests/ptests/ptest_41b5466dabf23647.stdout
	modified:   tests/ptests/ptest_469e79a86c2c874f.stdout
	modified:   tests/ptests/ptest_46a8435d247c34c9.stdout
	modified:   tests/ptests/ptest_4b0ed60c44c669f.stdout
	modified:   tests/ptests/ptest_6e6893c2c2254622.stdout
	modified:   tests/ptests/ptest_72f8f65472fcd4fa.stdout
	modified:   tests/ptests/ptest_7d1cd636566df8cd.stdout
	modified:   tests/ptests/ptest_825e60e73630f857.stdout
	modified:   tests/ptests/ptest_8484317bd3add4dc.stdout
	modified:   tests/ptests/ptest_8becd3030ba5621c.stdout
	modified:   tests/ptests/ptest_8ece6263396deeab.stdout
	modified:   tests/ptests/ptest_abc83ec759ddab6.stdout
	modified:   tests/ptests/ptest_bbfc26a93fbe15a7.stdout
	modified:   tests/ptests/ptest_c4ead86a12b992a8.stdout
	modified:   tests/ptests/ptest_caa4e824b02fa569.stdout
	modified:   tests/ptests/ptest_cc209e82fa5f78eb.stdout
	modified:   tests/ptests/ptest_cee646e8f21997ad.stdout
	modified:   tests/ptests/ptest_de916a0d5867def3.stdout
	modified:   tests/ptests/ptest_e1033830f4720a6f.stdout
	modified:   tests/ptests/ptest_f261ab10a0ea20f.stdout
	modified:   tests/ptests/ptest_ffbdb9af2de10fa.stdout

no changes added to commit (use "git add" and/or "git commit -a")


</details>

**Comment by MartinFillon** [comment]
Gonna take a look at your branch if you allow me

**Comment by cafkafk** [comment]
From #974 
> If this PR passes the CICD, I will close [PR #933](https://github.com/eza-community/eza/pull/933).

Review/pr continues in #974

**Pull request closed without merging**
