### PR TITLE
refactor: replace `lazy_static` with `once_cell`

### PR DESCRIPTION
**Pull request by acuteenvy**
Parts of `once_cell` are already in `std`, and the `Lazy` part is going to be implemented later.
`clap` also depends on `once_cell`, so after the clap PR gets merged there's going to be one less dependency.

### CODE REVIEW

**Review by cafkafk — CHANGES_REQUESTED** [review]
I wonder if the lazy_static in #533 could be replaced as well, if so, would you be up for doing it, e.g. after it's merged as part of this PR?

**Comment by acuteenvy** [comment]
Sure, I can do it.

```rust
static RECURSIVE_SIZE_HASHMAP: Lazy<Mutex<HashMap<(u64, u64), u64>>> =
    Lazy::new(|| Mutex::new(HashMap::new()));
```

instead of

```rust
lazy_static! {
    static ref RECURSIVE_SIZE_HASHMAP: Mutex<HashMap<(u64, u64), u64>> = Mutex::new(HashMap::new());
}
```

Should I make a suggestion there or change it after it's merged?

**Comment by PThorpe92** [comment]
> Should I make a suggestion there or change it after it's merged?

It's up to you really. I think there have been a few changes requested already over there already

**Review by PThorpe92 — DISMISSED** [review]

**Comment by cafkafk** [comment]
This might cause issues with the just merged #533, will wait for CI

**Review by cafkafk — CHANGES_REQUESTED** [review]
This will require a fixup to work with latest source, shouldn't be too bad thou

**Review by cafkafk — APPROVED** [review]
Integration tests pass, and I couldn't find any regressions. Will merge after merging HEAD and CI being happy

**Pull request merged**
