### PR TITLE
Add more tests

### PR DESCRIPTION
**Pull request by MartinFillon**
As mentionned in issue #279 we need to improve test dir, which I did, I just need your help to regenerate the current nix and windows test to better match the new dir that is tested

### CODE REVIEW

**Review by cafkafk — CHANGES_REQUESTED** [review]
Had to change commit summaries from `tests` -> `test`. Regenerated nix tests.

This can merge when someone regenerates windows tests as mentioned.

**Comment by MartinFillon** [comment]
Maybe @Stetsed could help on that pr for the windows part

**Comment by MartinFillon** [comment]
@cafkafk Windows is done :smile:

**Review by cafkafk — APPROVED** [review]
Okai, cool, for some reason CI doesn't run on this, I'll have to fix that somehow... but lgtm :+1:

**Pull request merged**
