### PR TITLE
feat(args): Add short flag for --group-directories-first

### PR DESCRIPTION
**Pull request by TheBearodactyl**
4th time's the charm i guess. I wasn't planning on doing another one, but stupid github closed the last one without my knowledge and greyed out the reopen pr button

### CODE REVIEW

**Review by MartinFillon — APPROVED** [review]
Apart from lat time discussion on why `W` for the argument everything is fine with me. If @cafkafk is fine with it beig `-W`.

**Review by PThorpe92 — APPROVED** [review]

**Comment by PThorpe92** [comment]
If `-W` is what was decided on then LGTM :+1:

**Comment by MartinFillon** [comment]
fixed your commits, for your info if you need to merge main to your branch, please use either `git pull --rebase upstream main`
or use the rebase main button on the pr webpage, it can be accessed by using the small button on the right of the merge main button

**Comment by TheBearodactyl** [comment]
> fixed your commits, for your info if you need to merge main to your branch, please use either `git pull --rebase upstream main`
> or use the rebase main button on the pr webpage, it can be accessed by using the small button on the right of the merge main button

oh shit. thanks :D

**Comment by MartinFillon** [comment]
its okay everyone make mistake

**Review by cafkafk — CHANGES_REQUESTED** [review]
> Apart from lat time discussion on why `W` for the argument everything is fine with me. If @cafkafk is fine with it beig `-W`.

Honestly, I'm a bit meh about giving away a shortflag for this, it seems like something that most often would just exist in your alias. `W` could be useful for so many other things.

Another option might be a shorter flag than `group-directories-first`, but idk, feel like this whole thing should have been discussed first tbh.

**Comment by MartinFillon** [comment]
Well, personnally I am not against using `-W` because for the moment it is free, but I understand the point of saying, meh, what if.
> this whole thing should have been discussed first tbh.

I agree on that but iirc no issue was submitted before @TheBearodactyl just came with this, I might be off tho.

**Comment by cafkafk** [comment]
> Well, personnally I am not against using `-W` because for the moment it is free, but I understand the point of saying, meh, what if.

I mean we kinda are in this chasing our own tail of bad flags leading to more bad flags. E.g. `-F --classify` when `-c` and `-C` are available to be closer to ls, but then we aren't really true to ls anyways, so why pick flags that just don't make sense. I think it would be great post clap to consider flags very seriously, creating a ls compat mode, perhaps an exa compat mode, and then just making the flags actually good. 

Also just from like a general design perspective, from https://clig.dev/#arguments-and-flags

> Only use one-letter flags for commonly used flags, particularly at the top-level when using subcommands. That way you don’t “pollute” your namespace of short flags, forcing you to use convoluted letters and cases for flags you add in the future.

Of course, that's a guideline, not a law, but I think it's a very good guideline.

AND I could still be okay with some other solution, e.g. typing a long flag like that kinda sucks, and it could be made shorter, AND maybe there is a better short flag. But I'm not eager to introduce this without having had that discussion first because changing it will be a breaking change. And those suck, and everyone hates them, specially users.

**Comment by MartinFillon** [comment]
> post clap

Why not using the clap PR for that ? I mean it is waiting and it is the best time for this. As it will break a huge part of the code base already but will not be breaking (hopefully) for the user. 

I like that guideline tho, and I think that we need to enforce discussion about flags either in PRs like this or in issues if it is a request but without code. For the long argument part I think we could shorten some of the args but the point of having a long arg is that it is explicit.

**Comment by TheBearodactyl** [comment]
> Well, personnally I am not against using `-W` because for the moment it is free, but I understand the point of saying, meh, what if.
> > this whole thing should have been discussed first tbh.
> 
> I agree on that but iirc no issue was submitted before @TheBearodactyl just came with this, I might be off tho.

no, you're right

**Comment by cafkafk** [comment]
> Why not using the clap PR for that ?

I mean we could, I'm just scared of overloading the clap PR so much it becomes impossible to review. I feel like it would be best if we first did the clap PR mostly true to form to what we already have, and then after started changing flags. 

But yes it might break stuff for the user, which is also why we might consider going to pre-releases of some sort when we merge clap.

> I think that we need to enforce discussion about flags either in PRs like this or in issues if it is a request

Yea, I should probably write sections in the CONTRIBUTING.md about flags that say they first have to be discussed, same with icons perhaps.

> For the long argument part I think we could shorten some of the args but the point of having a long arg is that it is explicit.

We could potentially have both, although it could easily get messy ofc.

**Comment by MartinFillon** [comment]
> I mean we could, I'm just scared of overloading the clap PR so much it becomes impossible to review. I feel like it would be best if we first did the clap PR mostly true to form to what we already have, and then after started changing flags.

Well for that we need better tests which I aim for

> Yea, I should probably write sections in the CONTRIBUTING.md about flags that say they first have to be discussed, same with icons perhaps.

We can also add a section about adding integration tests when args/features are added in order to help the powertests.

**Comment by TheBearodactyl** [comment]
@cafkafk should i try to come up with a better short flag, or would it be better to just leave it without one?

**Comment by MartinFillon** [comment]
Well, I think that for the moment we fine without a short arg, but if you still want to contribute we have some good issues ready and waiting.

**Comment by TheBearodactyl** [comment]
> Well, I think that for the moment we fine without a short arg, but if you still want to contribute we have some good issues ready and waiting.

Oki :D

**Comment by MartinFillon** [comment]
> I'll probably also contribute to the clap pr by adding help headings, improving the command descriptions, and possibly finding better short flags for the other args (for example, -C)

If you want to do this, we shall maybe wait for the clap merging as stated before @cafkafk and I thinks that we shall not introduce too much braking changes with clap and first ensure it works well, in order to be able to classify well the issue that could result out of it.

**Pull request closed without merging**
