### PR TITLE
Add Width Option

### PR DESCRIPTION
**Pull request by gierens**
`ls` has a `-w/--width` option limiting the columns of the grid output. `exa/eza` only allows to specify the number of columns via the `COLUMNS` environment variable for some reason.

This adds the `-w/--width` option to the existing column limiting, meaning it behaves just like when specifying the `COLUMNS` variable, but with the `ls`-like command line argument. In case both `COLUMNS` and `-w`, then the cli option takes precedence.

The only difference to the `-w` option of `ls` is, that `ls -w 0` sets the columns to infinity, while here it goes back to automatic width detection just as for the `COLUMNS` variable.

Resolves https://github.com/ogham/exa/issues/1168

### CODE REVIEW

**Review by cafkafk — CHANGES_REQUESTED** [review]
- ~~This needs to include completions for fish and zsh as far as I can tell.~~
- ~~This needs to conform to conventional commits~~

**Comment by cafkafk** [comment]
I'll help with the summaries, maybe the completions

**Review by cafkafk — APPROVED** [review]
After testing this a bit I found two bugs #129, #130, but neither are a flaw introduced by this PR. Guess that alone makes the case for this being a useful feature :laughing: 

Testing seems to indicate this works as intended, and I like this addition a lot.

Thanks a lot for your contributions!

**Comment by gierens** [comment]
> I'll help with the summaries, maybe the completions

Ah great thank's :) ... When I skimmed the completion files they seemed kind of outdated, some flags missing, therefore I thought they are not maintained and skipped including the new option ... lazy me :D

**Pull request merged**
